spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rohit-0000/Microservices
          clone-on-start: true
server:
  port: 8083

